 
  export const lightMode = {
    PRIMARY: '#1abaff',
    LIGHT_PRIMARY: '#80D9FF',
    LIGHTER_PRIMARY: '#bcebff',
    SECONDARY: '#00354d',
    SKELETON: '#e5f7ff',
    APP_PRIMARY: '#41392F',
    APP_SECONDARY: '#F7F1E7',
    APP_PRIMARY_LIGHT: '#c2bfbd',
    LIGHT_MAIN_BACKGROUND: '#CFCFCF',
    BACKGROUND: '#FFF',
    DARK_BACKGROUND: '#e7e7e7',
    MAIN_BACKGROUND: '#f6f6f6',
    TEXT: '#000000',
    DARK_PRIMARY: '#00121a',
    WHITE: '#FFF',
  };
  export const darkMode = {
    PRIMARY: '#1abaff',
    LIGHT_PRIMARY: '#80D9FF',
    LIGHTER_PRIMARY: '#bcebff',
    SECONDARY: '#00354d',
    SKELETON: '#1abaff',
    LIGHT_MAIN_BACKGROUND: '#003247',
    APP_PRIMARY: '#41392F',
    APP_SECONDARY: '#F7F1E7',
    APP_PRIMARY_LIGHT: '#A7A3A0',
    BACKGROUND: '#001924',
    DARK_BACKGROUND: '#003247',
    MAIN_BACKGROUND: '#000a0e',
    TEXT: '#fff',
    DARK_PRIMARY: '#00121a',
    WHITE: '#FFF',
  };
 